# use C-a, since it's on home row and easier to hit than C-b
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix
set -g base-index 1
set -g mouse on

# split panes using | and -
# or v and s
bind | split-window -h
bind - split-window -v
bind-key v split-window -h
bind-key s split-window -v
bind r source-file ~/.tmux.conf
bind v copy-mode
# easier next / previous window
bind-key space next-window
bind-key enter next-window
bind-key bspace previous-window

set-window-option -g mode-keys vi

# vi keys for pane nav
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key [ copy-mode
bind-key ] paste-buffer

