
import { DynamicComponentManifest } from '@omelek/platform-core-base';
// This file was Automatically generated by lazyLoadGenerator.js
// This array defines which "componentId" maps to which lazy-loaded module.
export const manifests: DynamicComponentManifest[] = [
  
  {
    componentId: 'BlueprintComponent',
    path: 'BlueprintComponent',
    loadChildren: './dynamic-components/proxy-blueprint.module#BlueprintComponentLoader',
  },
  {
    componentId: 'GanttWidgetComponent',
    path: 'GanttWidgetComponent',
    loadChildren: './dynamic-components/proxy-ng-equipgantt-lib.module#GanttWidgetComponentLoader',
  },
  {
    componentId: 'EtnotesearchComponent',
    path: 'EtnotesearchComponent',
    loadChildren: './dynamic-components/proxy-etnotesearch.module#EtnotesearchComponentLoader',
  },
  {
    componentId: 'EtoolmonComponent',
    path: 'EtoolmonComponent',
    loadChildren: './dynamic-components/proxy-etoolmon.module#EtoolmonComponentLoader',
  },
  {
    componentId: 'EtoolmonSidenavComponent',
    path: 'EtoolmonSidenavComponent',
    loadChildren: './dynamic-components/proxy-etoolmon.module#EtoolmonSidenavComponentLoader',
  },
  {
    componentId: 'AdminWidgetContainerComponent',
    path: 'AdminWidgetContainerComponent',
    loadChildren: './dynamic-components/proxy-platform-core-admin.module#AdminWidgetContainerComponentLoader',
  },
];
export default manifests;
  