
import { NgModule } from '@angular/core';
import { EtoolmonModule,EtoolmonComponent,EtoolmonSidenavComponent } from '@omelek/etoolmon';
import { DynamicComponentLoaderModule } from '@omelek/platform-core-base';
// This file was Automatically generated by lazyLoadGenerator.js
// This defines proxy module.ts files for each lazy-loaded module and its components.
  
@NgModule({
  imports: [
    EtoolmonModule,
    DynamicComponentLoaderModule.forChild(EtoolmonComponent)
  ]
})
export class EtoolmonComponentLoader {}
  
@NgModule({
  imports: [
    EtoolmonModule,
    DynamicComponentLoaderModule.forChild(EtoolmonSidenavComponent)
  ]
})
export class EtoolmonSidenavComponentLoader {}
  