
import { NgModule } from '@angular/core';
import { BlueprintModule,BlueprintComponent } from '@omelek/blueprint';
import { DynamicComponentLoaderModule } from '@omelek/platform-core-base';
// This file was Automatically generated by lazyLoadGenerator.js
// This defines proxy module.ts files for each lazy-loaded module and its components.
  
@NgModule({
  imports: [
    BlueprintModule,
    DynamicComponentLoaderModule.forChild(BlueprintComponent)
  ]
})
export class BlueprintComponentLoader {}
  