
import { NgModule } from '@angular/core';
import { GanttModule,GanttWidgetComponent } from '@omelek/ng-equipgantt-lib';
import { DynamicComponentLoaderModule } from '@omelek/platform-core-base';
// This file was Automatically generated by lazyLoadGenerator.js
// This defines proxy module.ts files for each lazy-loaded module and its components.
  
@NgModule({
  imports: [
    GanttModule,
    DynamicComponentLoaderModule.forChild(GanttWidgetComponent)
  ]
})
export class GanttWidgetComponentLoader {}
  