
import { NgModule } from '@angular/core';
import { EtnotesearchModule,EtnotesearchComponent } from '@omelek/etnotesearch';
import { DynamicComponentLoaderModule } from '@omelek/platform-core-base';
// This file was Automatically generated by lazyLoadGenerator.js
// This defines proxy module.ts files for each lazy-loaded module and its components.
  
@NgModule({
  imports: [
    EtnotesearchModule,
    DynamicComponentLoaderModule.forChild(EtnotesearchComponent)
  ]
})
export class EtnotesearchComponentLoader {}
  