
import { NgModule } from '@angular/core';
import { PlatformCoreAdminModule,AdminWidgetContainerComponent } from '@omelek/platform-core-admin';
import { DynamicComponentLoaderModule } from '@omelek/platform-core-base';
// This file was Automatically generated by lazyLoadGenerator.js
// This defines proxy module.ts files for each lazy-loaded module and its components.
  
@NgModule({
  imports: [
    PlatformCoreAdminModule,
    DynamicComponentLoaderModule.forChild(AdminWidgetContainerComponent)
  ]
})
export class AdminWidgetContainerComponentLoader {}
  