FROM ubuntu:latest
# FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:14

########################################
# System Stuff
########################################

# Better terminal support
ENV TERM=screen-256color \
    DEBIAN_FRONTEND=noninteractive \
    HTTP_PROXY=http://proxy-web.micron.com:80 \
    HTTPS_PROXY=http://proxy-web.micron.com:80 \
    http_proxy=http://proxy-web.micron.com:80 \
    https_proxy=http://proxy-web.micron.com:80 \
    NO_PROXY=.micron.com \
    PATH=$HOME/node_modules/.bin/:$HOME/.npm-global/bin/:$PATH

COPY ./microncert.crt /usr/local/share/ca-certificates/microncert.crt
COPY ./.npmrc /root/.npmrc

RUN apt-get update \
    && apt-get install -y \
    ca-certificates \
    apt-file \
    && apt-file update

# Update and install
RUN update-ca-certificates \
      && apt-get update \
      && apt-get install -y \
      git \
      git-core \
      sudo \
      gnupg \
      build-essential \
      fonts-powerline \
      openssh-client \
      htop \
      curl \
      wget \
      rsync \
      unzip \
      zip \
      less \
      nano \
      locales \
      bash \
      software-properties-common \
      python-dev \
      python3-dev \
      python3-pip \
      ctags \
      shellcheck \
      netcat \
      ack-grep \
      sqlite3 \
      unzip \
      vim \
      zsh \
      nodejs \
      npm \
      tmux \
      # For python crypto libraries
      libssl-dev \
      libffi-dev

# Generally a good idea to have these, extensions sometimes need them
ENV locale-gen=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

# Install Neovim
RUN add-apt-repository ppa:neovim-ppa/stable
RUN apt-get update && apt-get install -y \
      neovim
########################################
# Python
########################################

# Install python linting and neovim plugin
#ADD py2_requirements.txt /opt/py2_requirements.txt
#RUN cd /opt && pip2 install -r py2_requirements.txt

ADD py3_requirements.txt /opt/py3_requirements.txt
RUN cd /opt && pip3 install -r py3_requirements.txt

ENV PATH=/app/node_modules/.bin:$PATH \
    NODE_OPTIONS=--max_old_space_size=8048

RUN npm install -g @angular/cli@11.1.4 typescript ts-node prettier neovim eslint cloc @omelek/xweb-cli @omelek/platform-core-cli

########################################
# Personalizations
########################################
# Add some aliases
ADD bashrc /root/.bashrc
# Add my git config
# ADD gitconfig /etc/gitconfig
# Change the workdir, Put it inside root so I can see neovim settings in finder
RUN sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
Add .zshrc /root/

ADD nvim /root/.config/nvim

WORKDIR /app
# Neovim needs this so that <ctrl-h> can work
# RUN infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > /tmp/$TERM.ti
# RUN tic /tmp/$TERM.ti
# Add nvim config. Put this last since it changes often
# Install neovim plugins
RUN nvim -i NONE -c PlugInstall -c quitall > /dev/null 2>&1

RUN nvim -i NONE -c 'CocInstall -sync coc-emmet coc-css coc-html coc-json coc-prettier coc-tsserver coc-snippets coc-eslint' -c quitall > /dev/null 2>&1

RUN chsh -s $(which zsh)
# Command for the image
CMD ["/bin/bash"]
# RUN cd /root/.config/nvim/plugged/YouCompleteMe && python3 install.py
# Add flake8 config, don't trigger a long build process
# ADD flake8 /root/.flake8
# Add local vim-options, can override the one inside
# ADD vim-options /root/.config/nvim/plugged/vim-options
# Add isort config, also changes often
# ADD isort.cfg /root/.isort.cfg
# Add ranger config
# ADD rc.conf /root/.config/ranger/rc.conf
