FROM iteng-docker-dev.boartifactory.micron.com/omelek/testbed-ng11-dev:latest
FROM iteng-docker-dev.boartifactory.micron.com/omelek/neovim:latest
WORKDIR /app
COPY --from=0 /app/node_modules /app/node_modules
CMD ["/bin/bash"]
